# Generated by Django 5.2.5 on 2025-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram_available',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_free',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='storage_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='process',
            name='cpu_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='process',
            name='memory_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='process',
            name='parent_pid',
            field=models.IntegerField(null=True),
        ),
    ]
